# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Jayanth Kumar A K
description: Welcome to my site. I am a graduate student at UW. I am a product professional with interests in information security, good experience design and usability. My career aims are to learn skills and experiences to create the future. Please get in touch or check out some of my work and musings.
github_username: jayanthkumarak

# Email and twitter are optional:
email: jayanthk@uw.edu
twitter_username: 

# Set this to true to get LaTeX math equation support
use_math: 

# Everything below here can be ignored, unless you want to change the theme entirely
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-octicons

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
